# Generated by Django 6.0.7 on 2026-07-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(default=0.0)),
                ('driver_name', models.CharField(default='John Doe', max_length=255)),
                ('tractor_number', models.CharField(default='TRK-101', max_length=255)),
                ('trailer_number', models.CharField(default='TRL-202', max_length=255)),
                ('carrier_name', models.CharField(default='Apex Logistics', max_length=255)),
                ('shipping_doc', models.CharField(default='BOL-1001', max_length=255)),
                ('commodity', models.CharField(default='General Freight', max_length=255)),
                ('start_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_miles', models.FloatField(default=0.0)),
                ('total_hours', models.FloatField(default=0.0)),
                ('final_cycle_hours', models.FloatField(default=0.0)),
                ('full_data_json', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
